CREATE TABLE Client (
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(50),
	company VARCHAR(50),
);

CREATE TABLE Sale (
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	client_id INT NOT NULL FOREIGN KEY REFERENCES Client(id),
	product VARCHAR(50),
);